### ISSUE TITLE
Best place to enable bit packing, and when to align?

### ISSUE THREAD

**Issue by Net5F** [fraillt/bitsery#119]
If I have a struct that holds a container of structs that will bit-pack some members:
```
struct Parent {
    std::vector<Element> container{};
};

struct Element{
    int first{};
    bool second{};
};

template<typename S>
void serialize(S& serializer, Parent& parent) {
    serializer.container(parent.container);
}

template<typename S>
void serialize(S& serializer, Element& element) {
    serializer.value4b(element.first);
    serializer.boolValue(element.second); // Want to bit-pack this so it matches MeasureSize
}
```
Where's the most efficient place to first enable bit packing, and do I need to align anywhere?
This is sort-of asking the questions: 
1. If I enable bit packing at the highest level (Parent), does that incur any cost when serializing the types that don't need to be bit packed?
2. I believe that the destruction of the bit-packing wrapper causes an align. Is it also beneficial to manually align anywhere? For example, if I have multiple bit-packed members in a struct, should I put all of their serialization close together and call align before serializing any non-bit-packed members, or the members of the next struct in the container?

**Comment by fraillt** [comment]
Once you enable bit-packing all operations will at least have one extra check (if current write position is aligned), and there is also additional cost if actual write position is not aligned.
However, enabling bit packing itself is basically free, because it is enforced statically, and moving buffer to other adapter is usually optimized.
My advice would be to enable bit-packing when you really need it, and if you notice that you need to compress more, you can always enable in parent as well (enabling it in child will be no-op, and it will not be aligned on drop if parent is still in bit packing mode)
When it comes to performance, in terms of CPU it will definitely cost more, but if your data can be compressed quite well, in the end overall performance can be better.
In case you are not aware, there are several extensions that help to save space: compact_value.h, value_range.h, entropy.h.

Have fun:)

**Comment by Net5F** [comment]
Awesome, I think that clears it all up. Thanks!
