### ISSUE TITLE
static_assert error in flexible.h with rvalue to serialize

### ISSUE THREAD

**Issue by Luli2020** [fraillt/bitsery#17]
In our application there were cases that requires different implementations of serial/deserialization, and my solution is to write separate “serialize” functions with the Serializer class (non-template). In the serialization function, I encountered the errors when using the flexible format and it is something like:
'
…
using StreamedSerializer =
    bitsery::BasicSerializer<bitsery::AdapterWriter<OutputStreamAdapter, bitsery::DefaultConfig>, TContext>;
int get_test(const Test&t){return t.data_int;}

void serialize(StreamedSerializer &ar, const Test &t) {  
    ar.archive(t.data_int);//ok
    ar.archive(static_cast<double>(t.data_int));//fail
    ar.archive(get_test(t));//fail
}
…
'
The failure cases is giving the following error:
“bitsery/include/bitsery/flexible.h:44:13: error: static_assert failed due to requirement 'std::is_base_of<ArchiveWrapperFnc, int>::value' "\nOnly archive behaviour modifying functions can be passed by rvalue to deserializer\n”

If I removed the assertion statement, things are actually WORKING fine. I guess the static assertion is to make sure the serialize function works for both serial/deserializing functions. However, in our code there were some complicated cases (including third party libraries) using rvalues for serializing, so I am wondering is there any better way (if not removing the assertion) to make this case work?
Thanks a lot!
Lu

**Comment by fraillt** [comment]
Hello,
Yes, there is a better way, and it is to write your own "extension" :)
Extensions were created for exactly this purpose,- to customise serialization and deserialization flow.
Keep in mind that you can mix flexible and normal syntax. So instead of defining 2 non-templated serialize functions, you can create an extension and use it like this:
```cpp
template <typename Archive>
void serialize(Arhive& ar, MyComplicatedType& o) {
  ar.archive(o.simple1, o.simple2);
  ar.ext(o.complex1, MyExtForComplex1{});
}
```
I definitely need to write a tutorial on how to create extensions, but for now you can try to look at bitsery extensions at `include/bitsery/ext`.
Btw, we can chat on [gitter](https://gitter.im/bitsery/Lobby), I could help you to write your first extension:)

**Comment by Luli2020** [comment]
Great, I implemented as this approach and it works, thanks a lot. However there is still one more problem since our third party library is taking the serializer as parameter and do the serialization, and in their  templated serialization functions they used rvalues, say something like "ar.archive(static_cast<int>(t));", and so the assertion error as I mentioned in previous post still exists. Is there any better way to do other than removing the assertion?

**Comment by fraillt** [comment]
Passing by an rvalue will only work in serialization. In order to deserialize you need to pass by a lvalue, otherwise, there is no point to deserialize in a temporary object.
If it's fine, that this third-party library function only works for serialization, and you need to write your own for deserialization (or maybe you don't even need to deserialize?), then I think it is fine to remove the assertion.
Btw, what is the purpose of these static_casts? can you ask a third-party library maintainer to fix this? :)

**Comment by Luli2020** [comment]
I think that is some error in my code. After I check again, things are working fine. Thank you so much for your time and answers!

**Comment by fraillt** [comment]
A working solution was provided in #18
