### ISSUE TITLE
[Question] What is the structure of the binary stream after serialize?

### ISSUE THREAD

**Issue by tan-wei** [fraillt/bitsery#21]
Thanks for this awesome project!

Forgive me that I haven't read the source code but documents. I have a question about the serialize result of `bitsery`. What's the structure of the binary stream? Could you explain it briefly?

Thank you very much! Hope you have a nice day.

**Comment by fraillt** [comment]
Hello,
In short, there is no "structure" only raw data.
You have probably noticed that bitsery serialized "data size" is very small compared to other serialize frameworks. To achieve this, bitsery follows two rules.
1) All metadata (or structure as you name it) is defined in your code. Bitsery doesn't need to write name or type of variable in a stream, because it already has this information in code.
2) For container like types (array, string vector, etc) write as small bytes as possible for container size value.
E.g. you want to serialize `std::vector<int16> data {1,2,3};` in stream it will look like this:
1byte for container size (because vector is short enough to write "3" in one byte)
3*2 for data (3 variables * 2 bytes each),
in total 7bytes.
Hope it is clearer now ;)

**Comment by tan-wei** [comment]
Pretty clear for me. Thank you very much.
But I hvae another question about a special kind of binary stream. 
Can we use `bitsery` to serialise a structure which contains arbitrary bits types? E.g:
```c
struct {
  X x;
  Y y;
  Z z;
  U u;
  V v;
} Foo;
```
After use serialization using `bitsery` with `Foo`, will produce the stream below (`X x` will produce `xxx` which means 3 bit length):
```
| xxxy yyyy yyyz zzzz zzuu uvvv vvvv ... |
```

Can we do this? Thanks very much! Hope you have a nice weekend.

**Comment by fraillt** [comment]
Yes, you can do that as well, all you need is to enable bit packing, and use `ValueRange` extension, see [bit packing example](https://github.com/fraillt/bitsery/blob/master/examples/bit_packing.cpp), or [tests](https://github.com/fraillt/bitsery/blob/master/tests/serialization_ext_value_range.cpp)

Have fun ;)

**Comment by tan-wei** [comment]
Wow, fantastic! Thanks for your kind reply and the fantastic project! :-P
