### ISSUE TITLE
Stop writing on non-resizable buffer overflow

### ISSUE THREAD

**Issue by sepiacolor** [fraillt/bitsery#26]
Hi, first off I wanna say I've been playing around with your library for a few days and I'm quite liking it. Keep up with the good work!

Now, I don't know if it's a bug or the behavior is intended, but serialization keeps writing on a non-resizable buffer even when the buffer limit is exceeded. I'm planning to use your library in a network application where the buffer size of network messages has a max size known at compile time but message data can vary and possibly overflow the buffer limit, in which case I'd like to both stop the serialization and know the serialization wasn't completed, which I think is how it should be for all cases of non-resizable buffers? Reading your code, I see you're simply `assert()`ing the distance between iterators in `OutputBufferAdapter::writeInternalImpl()` for non-resizable buffers. So I changed it to this:

```cpp
void writeInternalImpl(const TValue *data, size_t size, std::false_type) {
    //optimization

    //assert(std::distance(_outIt + size, _end) >= 0);

    if (std::distance(_outIt + size, _end) < 0)
        throw 1; // couldn't serialize, reached non-resizable buffer limit
            
    memcpy(std::addressof(*_outIt), data, size);
    _outIt += size;
}
```

And it works as I expect. But it seems that you have designed your library so as to not throw exceptions, so maybe you could add an enum class `WriterError` (for symmetry with `ReaderError`) and let the user code call `error()` to check if serialization succeeded.

**Comment by fraillt** [comment]
I'm glad you liked it, hope that bitsery will help you solve your problems:)
Asserts on serialization is indeed intensional, because you should be in control of your code to make sure it has works. However, in this situation it seam reasonable to return error as well, although performance might drop by few percents in release mode due to additional boundary checks:)
Currently I can suggest two options for you:
1. You can try to use MeasureSize adapter to check for size, before writing to real buffer.
2. You can implement your own output buffer adapter if you don't want to modify a library.

I'm not sure if introducing WriterError is good idea, apart from this usecase...

**Comment by fraillt** [comment]
Asserts are used for serialization, and error codes for deserialization.
Since this can be solved easily, I will not introduce an exception to this, so I just close the issue.
