### ISSUE TITLE
mishandles doubly linked lists?

### ISSUE THREAD

**Issue by Swoboderz** [fraillt/bitsery#27]
```cpp
struct Object {
	int32_t i = 25;
    
    Object* m_next;
    Object* m_prev;
	bool operator== (Object other){
		if(other.i == i){
			return true;
		}
		return false;
	}
};
template <typename S>
void serialize(S& s, Object& o){
    s.value4b(o.i);
    s.ext(o.m_next,PointerObserver{PointerType::Nullable});
    s.ext(o.m_prev,PointerObserver{PointerType::Nullable});
}
struct MyStruct {
  Object* ptr;
  int32_t object_count = 0;
};
template <typename S>
void serialize(S& s, MyStruct& o) {
    s.value4b(o.object_count);
    for(Object* start = o.ptr; start != nullptr; start = start->m_next){
        s.ext(start,PointerOwner{PointerType::NotNull});
    }
};
```

Assertion failed: (state.first == ReaderError::NoError && state.second), function main, file src/main.cpp, line 95.

**Comment by fraillt** [comment]
I don't see how your `void serialize(S& s, MyStruct& o)` implementation should work for deserialization.
Avoid using loops, and conditionals directly in `serialize` function, because it will most likely not work for serialization and deserialization flow. 
Instead write your own extension, and customise serializiation and deserialization flow separately in the extension.
Your current implementation should work for serialization, but not for deserialization.

**Comment by fraillt** [comment]
Since there are no further questions, I assume that @Swoboderz has fixed its issues.
