### ISSUE TITLE
Does it work in arduino?

### ISSUE THREAD

**Issue by akshar001** [fraillt/bitsery#3]

**Comment by akshar001** [comment]
I have tried basic example in arduino and it's working very fine...don't know other commands but i think this library for arduino is going to rock!

**Comment by fraillt** [comment]
Nice!
I wasn't able to make it work, because of missing multiple c++ standard headers.
I simply installed an official Arduino package and was using [arduino-cmake](https://github.com/arduino-cmake/arduino-cmake) to build it, but immediately get `type_traits: No such file or directory` ...
Could you guide me, how to make it work? :)
