### ISSUE TITLE
const input buffer

### ISSUE THREAD

**Issue by gotocoffee1** [fraillt/bitsery#31]
Hey, cool Lib,
But I wanna ask, if there is a reason, why the bitsery::InputBufferAdapter only works with non const iterators?

**Comment by fraillt** [comment]
Hi,
I'm glad you like it ;)
But that you're asking is easier said than done.
The problem is that const and non-const iterator has different types for non-const buffer type, and InputBufferAdapter depends only on buffer type(it needs buffer type, to get additional information from BufferAdapterTraits), and not on iterator type.
However, you can specify const buffer type, as template parameter for InputBufferAdapter, in this case it should work with const iterator.
e.g.
```cpp
using Buffer = std::vector<uint8_t>;
using Reader = InputBufferAdapter<const Buffer>; // make buffer type const
...
Buffer buf{};
...
Deserializer<Reader> des(buf.begin(), buf.end()); // works
...
Deserializer<Reader> des(buf.cbegin(), buf.cend()); // also works
```

Hope that helped.

**Comment by gotocoffee1** [comment]
Thank you, it works perfect. 👍
