### ISSUE TITLE
iterator out of range

### ISSUE THREAD

**Issue by gotocoffee1** [fraillt/bitsery#34]
Well I didnt know that either but it seems thats iterrating an iterrator outside of the container range [is UB](https://stackoverflow.com/questions/28408649/incrementing-iterator-out-of-range).

An assert triggers in the [readChecked ](https://github.com/fraillt/bitsery/blob/master/include/bitsery/adapter/buffer.h#L148) function, on msvc 2017 in Debug mode.

**Comment by fraillt** [comment]
Hello,
Well, I guess you're right it is UB. Although, we know that we have an iterator to char* buffer basically, so unless the compiler decides to make some sort of fancy optimization instead of executing arithmetic operations on the pointer, we're fine.
However, rewrote buffer adapters, to use arithmetic operations on integral types, instead of iterators, so I'll release a new bitsery version tomorrow!

**Comment by fraillt** [comment]
fixed in [v5.0.3](https://github.com/fraillt/bitsery/releases/tag/v5.0.3)
