### ISSUE TITLE
isCompletedSuccesfully() for InputStreamAdaptor

### ISSUE THREAD

**Issue by pgruenbacher** [fraillt/bitsery#35]
This returns false even if all data is succesfully read https://github.com/fraillt/bitsery/blob/d24dfe14f5a756c0f8ad3d56ae6949ecc2c99b2e/include/bitsery/adapter/stream.h#L70

My guess is because the last data read in was a container with trailing empty data that was not read in, and so the current char is not eof. I'd just have the check instead confirm that all remaining characters in the stream is blank data to the eof.

**Comment by fraillt** [comment]
I don't understand what "blank data to the eof" means. 
Why it is something else after you deserialize an object?
In case a stream has multiple objects, and you want to check if a particular object was deserialized successfully, call `error` method instead of `isCompletedSuccessfully`.
Hope that helps.

**Comment by pgruenbacher** [comment]
I tried to replicate in a small test case for you but was unable to, so I think this should be more of an issue on my end, and I can just always check the error value without worrying about isCompletedSuccessfully.
