### ISSUE TITLE
Are the serialized files cross-architecture (64/32 bits) and cross endianness? [using compact mode or flexible]

### ISSUE THREAD

**Issue by JonathasValeriano** [fraillt/bitsery#7]
You did a fine job on this lib. It's really amazing, congratulations!

I would like to know if in flexible or compact mode, there is compatibility of serialized files between 32/64 bit architectures.

Let's say I serialize something using 64-bit architecture (compact mode), can I perform deserialization of this file in a 32-bit architecture (also using compact mode)?

Another issue is with regard to endianness, the serialized files in modes (flexible or compact) are cross endianness?

Thank you.

---------------------------
EDIT:

I found the information in the file containing the "motivation".

"Cross-platform compatible. if same code compiles on Android, PS3 console, and your PC either x64 or x86 architecture, you are 100% sure it works. To achieve this, bitsery specifically defines size of underlying data, hence syntax is value<2> (alias function value2b) instead or value, or container2b for element type of 16bits, eg int16_t. Bitsery also applies endianess transformation if nessesarry."

**Comment by fraillt** [comment]
Thanks, I'm glad that you find this lib useful :)
Regarding your question:
* Endianness is always enabled, default is LittleEndian, defined in [bitsery::DefaultConfig](https://github.com/fraillt/bitsery/blob/master/include/bitsery/common.h). When endianness matches host machine there is zero overhead for this feature, but if you want best performance on big endian platform (e.g. PS3), I recommend to change DefaultConfig (example on how to change config is [here](https://github.com/fraillt/bitsery/blob/master/examples/forward_backward_compatibility.cpp)). 
* When using *bitsery/flexible*, compatibility between 32 and 64 bit architectures is not enforced, because this syntax doesn't provide explicit sizes for fundamental types. However, there is *assertFundamentalTypeSizes* function that asserts fundamental types sizes. Code example is [here](https://github.com/fraillt/bitsery/blob/master/examples/flexible_assert_linux_x64.cpp) more info on c++ fundamental types and their sizes is [here](https://en.cppreference.com/w/cpp/language/types).

Hope that helps, 
If you have any questions, suggestions or comments, you can also write on [Gitter](https://gitter.im/bitsery/Lobby) :)
