### ISSUE TITLE
Lambdas 

### ISSUE THREAD

**Issue by victorstewart** [fraillt/bitsery#8]
any way to serialize lambdas? I can't really think of a way to lol.

**Comment by fraillt** [comment]
I'm not sure what you're trying to achieve.
Can you give me a small example?

**Comment by victorstewart** [comment]
I mean being able to serialize something like this (assuming the lamba only does copy captures, but may call on some class static functions and variables).

```
class ClassWithLambda {
private:

	constexpr static auto lambaPrototype = [] (uint8_t *buffer, size_t bufferSize) -> void { bufferSize += 1; };

public:

	typedef decltype(lambaPrototype) LambaType;

	uint8_t *buffer
	size_t bufferSize;
	LambaType callback;

};
```

**Comment by fraillt** [comment]
I'm still not sure what should be your final result, because your example doesn't compile either for multiple reasons :)
But if you make it compile, you can only serialize `buffer` and `bufferSize`. 
I'm afraid you cannot simply serialize internal lambda state, you have no control of it outside of lambda itself. 
In theory you could reinterpret cast (bit_cast in c++20 will not work either, because lambda will not be trivially copyable) lambda to a handwritten structure that reflect lambda capture clause and serialize it, but in practice its UB...

If you find a working solution for your problem, please share with us;)

**Comment by victorstewart** [comment]
haha my bad I whipped it up quick to share what I had in mind.

ya my assumption was that this was not possible to do directly, but just wanted to be sure! 

I easily worked around needing to do this, but if I ever happen upon a way to accomplish it I sure will share it.
