### ISSUE TITLE
Dynamic polymorphic class registration

### ISSUE THREAD

**Issue by BotellaA** [fraillt/bitsery#9]
I would like to know how to dynamically extend bitsery polymorphism. Let's take your example and assume this code is in a library A:
```
template<>
struct PolymorphicBaseClass<Shape> : PolymorphicDerivedClasses<Circle, Rectangle> {
};
```
Now, in another library B, I would like to add another class `Square` derived from `Shape`.
Is it possible to register this new relationship between `Square` and `Shape` without modifying the library A which does not know `Square`?

**Comment by fraillt** [comment]
Hello,
You can achieve that by registering polymorphic classes with `PolymorphicContext` instance calling `registerBasesList` method.
However, the problem is that this method creates a hierarchy using types described by `PolymorphicBaseClass`.
Let's say you have two libs A and B:
```cpp
//libA
template<>
struct PolymorphicBaseClass<Shape> : PolymorphicDerivedClasses<Circle, Rectangle> {
};
//libB
template<>
struct PolymorphicBaseClass<Shape> : PolymorphicDerivedClasses<MyNewShape> {
};
```
you'll be able to register classes only from lib, where PolymorphicBaseClass<Shape> is declared.

The only way, that I managed to achieve this, is by registering class hierarchy by hand (modifying `PolymorphicContext` and making `addToMap` method public) in lib where serialization happens, and registering my new types using `PolymorphicBaseClass` and `registerBasesList` in my executable, that use s this lib. 
In the process, I found that `registerBasesList` accepts serializer instance, when it only needs a type, which is really inconvenient, when I want to use `PolymorphicContext` context multiple times, and found compile error "multiple definition of bitsery::ext::pointer_utils::updatePLCInfo..." when using serializer in different libs, but solved it easily by moving functionality to bitsery::ext::pointer_utils::PLCInfo class.

**Comment by BotellaA** [comment]
By looking at your code, I also thought about registering by hand in the `PolymorphicContext` but as you said, this is not really allowed by the code at the moment.

Will you concider publishing the version you are refering to? With the `addToMap` public and cie? It will be a great help!

**Comment by fraillt** [comment]
After more investigation, I found a solution. What I need is to isolate a compiler generated symbols in different translation units. This involves two steps:
* put `PolymorphicBaseClass` primary template in the anonymous namespace, it is sufficient to hide only primary template in the anonymous namespace, other specializations can be defined without it (tested in GCC and clang)
* at invocation time `registerBasesList` function must get correct `PolymorphicBaseClass`. I was able to do it by assigning `PolymorphicBaseClass` as a default template parameter. 
```cpp
template<typename TSerializer, template<typename> class THierarchy = PolymorphicBaseClass, typename T1, typename ...Tn>
            void registerBasesList(PolymorphicClassesList<T1, Tn...>)
```

This should solve your problem, without manually registering class hierarchy, but in case you decide to register manually, I will add `registerSingleBaseBranch` method for that.
I'm planning to update **bitsery** today, and I'll also add new extension, **CompactValue** ;)

**Comment by fraillt** [comment]
As further investigation showed, this solution worked with clang, and failed to compile on GCC, and is not [standard compliant](https://stackoverflow.com/questions/3052579/explicit-specialization-in-non-namespace-scope).
So there is two options left:
1) make sure that you use `registerBasesList` only in one translation unit, and the the rest register manually with `registerSingleBaseBranch`.
2) make sure, that you use different types (same implementation as `PolymorphicBaseClass`) for declaring hierarchies in different translation units.
```cpp
//libA
template<>struct PolymorphicBaseClass<Shape> : PolymorphicDerivedClasses<Circle, Rectangle> {};
...
ctx.registerBasesList<MySerializer>(PolymorphicClassesList<Shape>{})

//libB
template<typename TBase>struct MyHierarchy {
    using Childs = PolymorphicClassesList<>;
};
template <> struct MyHierarchy<Shape>: PolymorphicClassesList<MySquare> {};
...
ctx.registerBasesList<MySerializer, MyHierarchy>(PolymorphicClassesList<Shape>{});
```
I just pushed new version, so all of this is available now.

**Comment by fraillt** [comment]
I have no plans to move to C++14.
I added this attribute for those who have newer compiler, so that I could inform them, but older compilers should ignored it and work without problem. If your compiler emits warning, maybe you could just ignore it or suppress it? :)
